// <auto-generated />
using System;
using CityPedidos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityPedidos.Infrastructure.Migrations
{
    [DbContext(typeof(PedidosDbContext))]
    partial class PedidosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CityPedidos.Domain.Entities.Core.Cliente", b =>
                {
                    b.Property<long>("nIdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nIdCliente"));

                    b.Property<bool>("bitEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtFechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtFechaEli")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtFechaMod")
                        .HasColumnType("datetime2");

                    b.Property<long>("nIdUsuarioCrea")
                        .HasColumnType("bigint");

                    b.Property<long?>("nIdUsuarioMod")
                        .HasColumnType("bigint");

                    b.Property<long?>("ndUsuarioEli")
                        .HasColumnType("bigint");

                    b.Property<string>("vApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vNombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vNumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nIdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Core.Pedido", b =>
                {
                    b.Property<long>("nIdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nIdPedido"));

                    b.Property<bool>("bitEstado")
                        .HasColumnType("bit");

                    b.Property<decimal>("decTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("dtFechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtFechaEli")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtFechaMod")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtFechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<long>("nIdCliente")
                        .HasColumnType("bigint");

                    b.Property<long>("nIdUsuarioCrea")
                        .HasColumnType("bigint");

                    b.Property<long?>("nIdUsuarioMod")
                        .HasColumnType("bigint");

                    b.Property<long?>("ndUsuarioEli")
                        .HasColumnType("bigint");

                    b.Property<string>("vNumeroPedido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nIdPedido");

                    b.HasIndex("nIdCliente");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Seguridad.Menu", b =>
                {
                    b.Property<long>("nIdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nIdMenu"));

                    b.Property<bool>("bitEstado")
                        .HasColumnType("bit");

                    b.Property<string>("vIcono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nIdMenu");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.Property<long>("nIdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nIdRol"));

                    b.Property<bool>("bitEstado")
                        .HasColumnType("bit");

                    b.Property<string>("vDescripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nIdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Seguridad.RolMenu", b =>
                {
                    b.Property<long>("NIdRol")
                        .HasColumnType("bigint");

                    b.Property<long>("nIdMenu")
                        .HasColumnType("bigint");

                    b.HasKey("NIdRol", "nIdMenu");

                    b.HasIndex("nIdMenu");

                    b.ToTable("RolMenus");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.Property<long>("nIdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("nIdUsuario"));

                    b.Property<bool>("bitEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dtFechaCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtFechaEli")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtFechaMod")
                        .HasColumnType("datetime2");

                    b.Property<long>("nIdRol")
                        .HasColumnType("bigint");

                    b.Property<long>("nIdUsuarioCrea")
                        .HasColumnType("bigint");

                    b.Property<long?>("nIdUsuarioMod")
                        .HasColumnType("bigint");

                    b.Property<long?>("ndUsuarioEli")
                        .HasColumnType("bigint");

                    b.Property<string>("vContrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vNombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nIdUsuario");

                    b.HasIndex("nIdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Core.Pedido", b =>
                {
                    b.HasOne("CityPedidos.Domain.Entities.Core.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("nIdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Seguridad.RolMenu", b =>
                {
                    b.HasOne("CityPedidos.Domain.Entities.Seguridad.Rol", "rol")
                        .WithMany("RolMenus")
                        .HasForeignKey("NIdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CityPedidos.Domain.Entities.Seguridad.Menu", "menu")
                        .WithMany("RolMenus")
                        .HasForeignKey("nIdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menu");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Seguridad.Usuario", b =>
                {
                    b.HasOne("CityPedidos.Domain.Entities.Seguridad.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("nIdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Seguridad.Menu", b =>
                {
                    b.Navigation("RolMenus");
                });

            modelBuilder.Entity("CityPedidos.Domain.Entities.Seguridad.Rol", b =>
                {
                    b.Navigation("RolMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
